# Site
repository: richimf
# favicon: images/favicon.ico

# Personal info
name: Ricardo Montesinos
title: Mobile Developer
email: ricardo.montesinos@globant.com
website: https://richimf.github.io

# Social links
#twitter_username: facespics
github_username:  richimf
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: ricardo-m-8942444b
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
I am a technology, game and design lover. Get on well with people at all levels, easily making good working relationships. Adaptable and quick to learn new skills.
I have been developing mobile apps since 5 years ago. My goal is to became in a great world level developer.

  I am most skilled in: <mark>iOS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Gaming
   - Knitting

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
